package cmd

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"neuron/internal/storage"

	"github.com/spf13/cobra"
)

var (
	techStack  string
	targetPath string

	initCmd = &cobra.Command{
		Use:   "init [project-name]",
		Short: "Initialize a new project scaffolded with high-signal context",
		Long:  `Creates a clean, standard project scaffold with a template-specific AGENTS.md file and instantly registers it with Neuron's DuckDB database.`,
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			projectName := args[0]
			tech := strings.ToLower(techStack)

			if tech != "go" && tech != "node" {
				return fmt.Errorf("unsupported tech stack '%s' (supported: go, node)", techStack)
			}

			p := targetPath
			if p == "" {
				p = filepath.Join(".", projectName)
			}

			absPath, err := filepath.Abs(p)
			if err != nil {
				return fmt.Errorf("failed to resolve absolute path: %w", err)
			}

			if err := os.MkdirAll(absPath, 0755); err != nil {
				return fmt.Errorf("failed to create directory %s: %w", absPath, err)
			}

			entries, err := os.ReadDir(absPath)
			if err == nil && len(entries) > 0 {
				hasFiles := false
				for _, entry := range entries {
					if entry.Name() != ".git" {
						hasFiles = true
						break
					}
				}
				if hasFiles {
					return fmt.Errorf("target directory %s is not empty", absPath)
				}
			}

			fmt.Printf("Scaffolding %s project in %s...\n", tech, absPath)

			if err := scaffoldProject(projectName, absPath, tech); err != nil {
				return fmt.Errorf("scaffolding failed: %w", err)
			}

			if err := generateAgentsContext(projectName, absPath, tech); err != nil {
				return fmt.Errorf("failed to generate AGENTS.md context: %w", err)
			}

			ctx := context.Background()
			proj := &storage.Project{
				ID:        projectName,
				Name:      projectName,
				Path:      absPath,
				TechStack: tech,
			}

			if err := store.AddProject(ctx, proj); err != nil {
				return fmt.Errorf("scaffolding succeeded but failed to register project in database: %w", err)
			}

			fmt.Printf("\nProject '%s' successfully initialized and registered!\n", projectName)
			fmt.Printf("Target directory: %s\n", absPath)
			return nil
		},
	}
)

func init() {
	initCmd.Flags().StringVarP(&techStack, "tech", "t", "go", "tech stack to use (go, node)")
	initCmd.Flags().StringVarP(&targetPath, "path", "p", "", "destination path (defaults to ./[project-name])")
	rootCmd.AddCommand(initCmd)
}

func scaffoldProject(name, path, tech string) error {
	switch tech {
	case "go":
		goModContent := fmt.Sprintf("module %s\n\ngo 1.22.0\n", name)
		if err := os.WriteFile(filepath.Join(path, "go.mod"), []byte(goModContent), 0644); err != nil {
			return err
		}

		mainContent := `package main

import "fmt"

func main() {
	fmt.Println("Hello, Neuron-Scaffolded Go Project!")
}
`
		if err := os.WriteFile(filepath.Join(path, "main.go"), []byte(mainContent), 0644); err != nil {
			return err
		}

		makefileContent := fmt.Sprintf(`build:
	go build -o %s main.go

test:
	go test ./...

run:
	go run main.go
`, name)
		if err := os.WriteFile(filepath.Join(path, "Makefile"), []byte(makefileContent), 0644); err != nil {
			return err
		}

	case "node":
		packageJSON := fmt.Sprintf(`{
  "name": "%s",
  "version": "1.0.0",
  "description": "Clean Node.js template generated by Neuron",
  "main": "index.js",
  "scripts": {
    "start": "node index.js",
    "test": "echo \"Error: no test specified\" && exit 0"
  },
  "dependencies": {}
}
`, name)
		if err := os.WriteFile(filepath.Join(path, "package.json"), []byte(packageJSON), 0644); err != nil {
			return err
		}

		indexContent := `console.log("Hello, Neuron-Scaffolded Node.js Project!");
`
		if err := os.WriteFile(filepath.Join(path, "index.js"), []byte(indexContent), 0644); err != nil {
			return err
		}
	}

	return nil
}

func generateAgentsContext(name, path, tech string) error {
	var agentsContent string

	switch tech {
	case "go":
		agentsContent = fmt.Sprintf(`# AGENTS.md - %s

## Tech Stack
- Framework: Standard Library Go
- Language: Go (Golang)
- Go Version: 1.22+

## Key Commands
- Build: ~make build~
- Run: ~make run~
- Run tests: ~make test~

## Code Style
- Use standard, idiomatic Go formatting (always run ~go fmt~).
- Handle errors explicitly and early (~if err != nil { return ... }~).
- Keep conditional block/loop nesting depth to at most 2 levels; refactor complex loops.

## Boundaries
### ✅ Always
- Run linter/tests before considering a task complete.
- Handle all return errors explicitly.

### ⚠️ Ask First
- Adding third-party package dependencies.
- Creating packages outside standard Go project conventions.

### 🚫 Never
- Commit secrets, credentials, or ~.env~ files.
- Bypass error returns using blank identifiers (~_~).
`, name)

	case "node":
		agentsContent = fmt.Sprintf(`# AGENTS.md - %s

## Tech Stack
- Runtime: Node.js
- Package Manager: npm (always use npm, never yarn/pnpm unless specified)
- Language: JavaScript (ES6+)

## Key Commands
- Start app: ~npm start~
- Run tests: ~npm test~

## Code Style
- Named exports preferred over default exports.
- Use async/await for asynchronous actions instead of raw promise chains.

## Boundaries
### ✅ Always
- Run ~npm test~ before declaring a task complete.
- Verify node dependencies are stored cleanly.

### ⚠️ Ask First
- Installing new npm package dependencies.
- Modifying major entry-point configurations.

### 🚫 Never
- Commit secrets, ~.env~ files, or private credentials.
- Force push to main branches.
`, name)
	}

	// Replace placeholders with real backticks
	agentsContent = strings.ReplaceAll(agentsContent, "~", "`")

	agentsPath := filepath.Join(path, "AGENTS.md")
	if err := os.WriteFile(agentsPath, []byte(agentsContent), 0644); err != nil {
		return err
	}

	claudePath := filepath.Join(path, "CLAUDE.md")
	_ = os.Remove(claudePath)
	if err := os.Symlink("AGENTS.md", claudePath); err != nil {
		if errCopy := os.WriteFile(claudePath, []byte(agentsContent), 0644); errCopy != nil {
			return fmt.Errorf("failed to create symlink and fallback copy: %w", errCopy)
		}
	}

	return nil
}
