package scaffold

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// ScaffoldProject creates a clean, standard project scaffold with basic template files.
func ScaffoldProject(name, path, tech, planTemplate string) error {
	switch tech {
	case "go":
		goModContent := fmt.Sprintf("module %s\n\ngo 1.22.0\n", name)
		if err := os.WriteFile(filepath.Join(path, "go.mod"), []byte(goModContent), 0644); err != nil {
			return err
		}

		mainContent := `package main

import "fmt"

func main() {
	fmt.Println("Hello, Neuron-Scaffolded Go Project!")
}
`
		if err := os.WriteFile(filepath.Join(path, "main.go"), []byte(mainContent), 0644); err != nil {
			return err
		}

		makefileContent := fmt.Sprintf(`build:
	go build -o %s main.go

test:
	go test ./...

run:
	go run main.go
`, name)
		if err := os.WriteFile(filepath.Join(path, "Makefile"), []byte(makefileContent), 0644); err != nil {
			return err
		}

	case "node":
		packageJSON := fmt.Sprintf(`{
  "name": "%s",
  "version": "1.0.0",
  "description": "Clean Node.js template generated by Neuron",
  "main": "index.js",
  "scripts": {
    "start": "node index.js",
    "test": "echo \"Error: no test specified\" && exit 0"
  },
  "dependencies": {}
}
`, name)
		if err := os.WriteFile(filepath.Join(path, "package.json"), []byte(packageJSON), 0644); err != nil {
			return err
		}

		indexContent := `console.log("Hello, Neuron-Scaffolded Node.js Project!");
`
		if err := os.WriteFile(filepath.Join(path, "index.js"), []byte(indexContent), 0644); err != nil {
			return err
		}

	case "html":
		indexHTML := `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Vanilla HTML/CSS/JS</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <div class="card">
        <h1>Hello, Neuron-Scaffolded Static Project!</h1>
        <p>A clean, vanilla HTML5, CSS3, and JavaScript workspace.</p>
    </div>
    <script src="script.js"></script>
</body>
</html>
`
		if err := os.WriteFile(filepath.Join(path, "index.html"), []byte(indexHTML), 0644); err != nil {
			return err
		}

		styleCSS := `body {
    margin: 0;
    font-family: system-ui, -apple-system, sans-serif;
    background-color: #09090b;
    color: #f4f4f5;
    display: flex;
    align-items: center;
    justify-content: center;
    min-height: 100vh;
}
.card {
    background-color: #18181b;
    border: 1px solid #27272a;
    border-radius: 8px;
    padding: 2rem;
    max-width: 400px;
    text-align: center;
    box-shadow: 0 4px 12px rgba(0, 0, 0, 0.5);
}
h1 {
    color: #00ff66;
    margin-top: 0;
    font-size: 1.5rem;
}
p {
    color: #a1a1aa;
    font-size: 0.875rem;
    line-height: 1.5;
}
`
		if err := os.WriteFile(filepath.Join(path, "style.css"), []byte(styleCSS), 0644); err != nil {
			return err
		}

		scriptJS := `console.log("Hello, Neuron-Scaffolded Plain HTML/CSS/JS Project initialized!");
`
		if err := os.WriteFile(filepath.Join(path, "script.js"), []byte(scriptJS), 0644); err != nil {
			return err
		}

		makefileContent := `run:
	@echo "Serving static files on http://localhost:8000 ..."
	python3 -m http.server 8000
`
		if err := os.WriteFile(filepath.Join(path, "Makefile"), []byte(makefileContent), 0644); err != nil {
			return err
		}

	case "powershell":
		scriptPS1 := fmt.Sprintf(`# script.ps1 - Scaffolded by Neuron

[CmdletBinding()]
param (
    [Parameter(Mandatory = $false)]
    [string]$Name = "%s"
)

Write-Host "=============================================" -ForegroundColor Green
Write-Host "Hello from $Name!" -ForegroundColor Green
Write-Host "PowerShell Engine version: $($PSVersionTable.PSVersion)" -ForegroundColor Green
Write-Host "=============================================" -ForegroundColor Green
`, name)
		if err := os.WriteFile(filepath.Join(path, "script.ps1"), []byte(scriptPS1), 0644); err != nil {
			return err
		}

		readmeMD := `# PowerShell Script Workspace

Scaffolded by Neuron.

## Execution Command
Run the script using:
` + "```powershell" + `
.\script.ps1
` + "```" + `
*Note: You may need to bypass standard execution policies in development: ` + "`Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass`" + `.*
`
		if err := os.WriteFile(filepath.Join(path, "README.md"), []byte(readmeMD), 0644); err != nil {
			return err
		}

	case "nextjs":
		packageJSON := fmt.Sprintf(`{
  "name": "%s",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "next": "^14.2.4",
    "react": "^18.3.1",
    "react-dom": "^18.3.1"
  },
  "devDependencies": {
    "typescript": "^5.4.5",
    "@types/node": "^20.14.2",
    "@types/react": "^18.3.3",
    "@types/react-dom": "^18.3.0"
  }
}
`, name)
		if err := os.WriteFile(filepath.Join(path, "package.json"), []byte(packageJSON), 0644); err != nil {
			return err
		}

		tsconfig := `{
  "compilerOptions": {
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [
      {
        "name": "next"
      }
    ],
    "paths": {
      "@/*": ["./src/*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
`
		if err := os.WriteFile(filepath.Join(path, "tsconfig.json"), []byte(tsconfig), 0644); err != nil {
			return err
		}

		srcDir := filepath.Join(path, "src")
		appDir := filepath.Join(srcDir, "app")
		if err := os.MkdirAll(appDir, 0755); err != nil {
			return err
		}

		globalsCSS := `body {
  background: #09090b;
  color: #f4f4f5;
  font-family: system-ui, sans-serif;
  margin: 0;
}
`
		if err := os.WriteFile(filepath.Join(appDir, "globals.css"), []byte(globalsCSS), 0644); err != nil {
			return err
		}

		layoutTSX := `import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Neuron Scaffolded Next.js App",
  description: "Generated by Neuron AI-Native Workspace Builder",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`
		if err := os.WriteFile(filepath.Join(appDir, "layout.tsx"), []byte(layoutTSX), 0644); err != nil {
			return err
		}

		pageTSX := `export default function Home() {
  return (
    <main style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', minHeight: '100vh', textAlign: 'center' }}>
      <h1 style={{ color: '#00ff66' }}>Hello, Neuron-Scaffolded Next.js App!</h1>
      <p style={{ color: '#a1a1aa' }}>Edit src/app/page.tsx to begin building your custom frontend.</p>
    </main>
  );
}
`
		if err := os.WriteFile(filepath.Join(appDir, "page.tsx"), []byte(pageTSX), 0644); err != nil {
			return err
		}

	case "python":
		mainPy := `def main():
    print("Hello, Neuron-Scaffolded Python Project!")

if __name__ == "__main__":
    main()
`
		if err := os.WriteFile(filepath.Join(path, "main.py"), []byte(mainPy), 0644); err != nil {
			return err
		}

		reqTxt := `# requirements.txt - Scaffolded by Neuron
# Add your third-party package dependencies here
`
		if err := os.WriteFile(filepath.Join(path, "requirements.txt"), []byte(reqTxt), 0644); err != nil {
			return err
		}

		makefileContent := `run:
	python3 main.py

test:
	python3 -m unittest discover -s . -p "*_test.py"
`
		if err := os.WriteFile(filepath.Join(path, "Makefile"), []byte(makefileContent), 0644); err != nil {
			return err
		}

	case "android":
		settingsGradle := `include ':app'
rootProject.name = "` + name + `"
`
		if err := os.WriteFile(filepath.Join(path, "settings.gradle"), []byte(settingsGradle), 0644); err != nil {
			return err
		}

		buildGradle := `buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.0.2'
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.8.21'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}
`
		if err := os.WriteFile(filepath.Join(path, "build.gradle"), []byte(buildGradle), 0644); err != nil {
			return err
		}

		appDir := filepath.Join(path, "app")
		srcDir := filepath.Join(appDir, "src", "main", "java", "com", "example", "neuronandroid")
		resLayoutDir := filepath.Join(appDir, "src", "main", "res", "layout")

		if err := os.MkdirAll(srcDir, 0755); err != nil {
			return err
		}
		if err := os.MkdirAll(resLayoutDir, 0755); err != nil {
			return err
		}

		appBuildGradle := `apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'

android {
    namespace 'com.example.neuronandroid'
    compileSdk 33

    defaultConfig {
        applicationId "com.example.neuronandroid"
        minSdk 24
        targetSdk 33
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.10.1'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.9.0'
}
`
		if err := os.WriteFile(filepath.Join(appDir, "build.gradle"), []byte(appBuildGradle), 0644); err != nil {
			return err
		}

		manifest := `<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="Neuron Android"
        android:theme="@style/Theme.AppCompat.Light">
        <activity
            android:name=".MainActivity"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>
</manifest>
`
		if err := os.WriteFile(filepath.Join(appDir, "src", "main", "AndroidManifest.xml"), []byte(manifest), 0644); err != nil {
			return err
		}

		mainActivity := `package com.example.neuronandroid

import android.os.Bundle
import androidx.appcompat.app.AppCompatActivity

class MainActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        android.util.Log.d("Neuron", "Hello, Neuron-Scaffolded Android App!")
    }
}
`
		if err := os.WriteFile(filepath.Join(srcDir, "MainActivity.kt"), []byte(mainActivity), 0644); err != nil {
			return err
		}

		layoutXML := `<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent">
    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="Hello, Neuron-Scaffolded Android App!"
        android:layout_centerInParent="true" />
</RelativeLayout>
`
		if err := os.WriteFile(filepath.Join(resLayoutDir, "activity_main.xml"), []byte(layoutXML), 0644); err != nil {
			return err
		}

		makefileContent := `build:
	./gradlew assembleDebug

test:
	./gradlew test

run:
	./gradlew installDebug
`
		if err := os.WriteFile(filepath.Join(path, "Makefile"), []byte(makefileContent), 0644); err != nil {
			return err
		}
	}

	// Write plan.md template from database
	planContent := strings.ReplaceAll(planTemplate, "[PROJECT_NAME]", name)
	if err := os.WriteFile(filepath.Join(path, "plan.md"), []byte(planContent), 0644); err != nil {
		return err
	}

	return nil
}

// GenerateAgentsContext generates a high-signal AGENTS.md and CLAUDE.md symlink.
func GenerateAgentsContext(name, path, tech, agentsTemplate string) error {
	agentsContent := strings.ReplaceAll(agentsTemplate, "[PROJECT_NAME]", name)

	// Replace placeholders with real backticks
	agentsContent = strings.ReplaceAll(agentsContent, "~", "`")

	agentsPath := filepath.Join(path, "AGENTS.md")
	if err := os.WriteFile(agentsPath, []byte(agentsContent), 0644); err != nil {
		return err
	}

	claudePath := filepath.Join(path, "CLAUDE.md")
	if err := os.Remove(claudePath); err != nil && !os.IsNotExist(err) {
		fmt.Printf("Warning: failed to clear CLAUDE.md: %v\n", err)
	}
	if err := os.Symlink("AGENTS.md", claudePath); err != nil {
		if errCopy := os.WriteFile(claudePath, []byte(agentsContent), 0644); errCopy != nil {
			return fmt.Errorf("failed to create symlink and fallback copy: %w", errCopy)
		}
	}

	// Setup Claude and OpenCode TUI skills path compatibility
	if err := EnsureTUICompatibility(path); err != nil {
		return fmt.Errorf("failed to configure dual-TUI compatibility directories: %w", err)
	}

	return nil
}
